pre_bump_hooks = [
	"buildozer 'set version {{version}}' //MODULE.bazel:%module",
	# Ecsact pre 1.0.0 the 0.X.0 is our 'major' version
	"buildozer 'set compatibility_level {{version.minor}}' //MODULE.bazel:%module",
]

post_bump_hooks = [
	"git push",
	"git push origin {{version}}",
	"gh release create {{version}} --generate-notes --latest -t {{version}} --verify-tag",
]
