name: Validate

on:
  push:
    branches:
      - "**"

jobs:
  check-module-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel-disk-cache
          key: ${{runner.os}}-bazel-cache
      - uses: actions/checkout@v4
      - name: Check Module Headers
        run: bazel run --config=ci //scripts:check_module_header
